apiVersion: v1
imagePullSecrets:
- name: haproxy-dockercfg-d64hg
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-03-21T11:13:58Z"
  name: haproxy
  namespace: test1
  resourceVersion: "69862"
  uid: c0f38c3a-d8f2-42da-bcf8-d8b415eab820
secrets:
- name: haproxy-dockercfg-d64hg
- name: haproxy-token-md25s

