apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testrb
  namespace: test1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: default 
  namespace: stom-apps-build
- kind: ServiceAccount
  name: haproxy 
  namespace: test1
