apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: asse-cc3r5e1-image-puller
  namespace: stom-apps-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: jbosseap
  namespace: asse-cc3r5e1
- kind: ServiceAccount
  name: default 
  namespace: asse-cc3r5e1
- kind: ServiceAccount
  name: haproxy 
  namespace: asse-cc3r5e1
